version: 0.2
phases:
  install:
     commands:
      - npm install
  pre_build:
    commands:
      - ln -s ../node_modules node_modules
  build:
    commands:
      - react-static build
  post_build:
    commands:
      - aws s3 sync --delete dist/ "s3://www.codekopp.com"