version: 0.2
phases:
  install:
     commands:
      - npm install -g
      - npm install -g --only-dev
      - ls -a
      - npm list -g --depth=0
  pre_build:
    commands:
  build:
    commands:
      - npm run build
      #- react-static build
  post_build:
    commands:
      - aws s3 sync --delete dist/ "s3://www.codekopp.com"