version: 0.2
phases:
  install:
    commands:
    - npm install
  pre_build:
    commands:
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" == "1" ]; then aws s3 sync --delete dist/ "s3://www.codekopp.com"; fi